config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'books/search', to: 'searchs#index', as: :search
  get 'books/store', to: 'searchs#store', as: :store
  get 'books/index', to: 'books#index', as: :books
  get 'books/:id/show', to: 'books#show', as: :book_show
  get 'books/liste/:id/show', to: 'listes#show', as: :liste_show
  patch 'books/liste/:id/update', to: 'listes#update', as: :liste_update

  patch 'books/:id/update', to: 'books#update', as: :book_update
  delete 'books/:id/destroy', to: 'books#destroy', as: :book_destroy
  post 'books/:id/notation', to: 'books#update_notation', as: :post_notation

  post 'books/:id/tags', to: 'books#update_tag', as: :book_update_tag, defaults: {format: :json}
  post 'books/:id/like', to: 'books#update_like', as: :book_update_like, defaults: {format: :json}
  post 'books/searchAuthor', to: 'searchs#searchAuthor', as: :author_search, defaults: {format: :json}
  post 'admin/delete', to: 'admins#delete', as: :admin_delete, defaults: {format: :json}
  get 'admin/add', to: 'admins#add', as: :admin_add
  get 'admin/liste/store', to: 'admins#store', as: :admin_liste_store
  post 'admin/storeNewListe', to: 'admins#storeListe', as: :admin_store_liste

  get 'books/:id/notations', to: "notations#index", as: :notations
  get 'books/:id/reviews/new', to: "reviews#new", as: :new_review
  post 'books/:id/reviews/new', to: "reviews#create"
  delete 'books/:id/reviews/:id', to: "reviews#destroy"
  get 'books/:id/reviews', to: "reviews#index", as: :reviews
  get 'books/:id/consultReviews', to: "reviews#consult", as: :review_consult
  get 'books/:id/consultNotations', to: "notations#consult", as: :notation_consult
  get 'books/:id/viewnote', to: "notations#view", as: :view_note
  get 'books/:id/viewcomment', to: "reviews#view", as: :view_comment
  get 'books/:user/profil', to: "profils#show", as: :profil_show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'books/:user/followers', to: "followers#create", as: :add_follower
  get 'books/followers', to: "followers#index", as: :view_followers
  delete 'books/:user/followers', to: "followers#destroy", as: :destroy_follower

  post "books/:id/comment", to: "reviews#comment", as: :review_comment



  get "books/historique", to: "historiques#index", as: :historique
  get "books/admin", to: "admins#index", as: :admin


  resources :readings do
    resources :reviews, only: ['new','create']
  end

  namespace :user do
    root :to => "books#index"
  end



end

app/views/shared/_carousel.html.erb
<style>
  .item {
    width: 160px;
    height: 200px;
    margin-right: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    border: 1px solid white;
    background-color: black;
  }

  .owl-carousel {
    display: flex;
    width: auto;
    padding: 0 15px;
  }

  img {
    width: 100%;
    height: 100%;
  }
</style>

<div class="owl-carousel">
  <%= link_to search_path(status: status) do  %>
    <% if ajout %>
      <div class="item" style="background-color: #B0C4DE;display: flex;flex-direction: column;">
        <i class="fas fa-book-reader" style="font-size: 2rem;color: blue"></i>
        <div style="font-size: 4rem;color: blue">+</div>
      </div>

    <% end %>
  <% end %>

  <% if status == 'livre' %>

    <% ec.each do |book| %>
      <%= link_to liste_show_path(book, status: status) do  %>
        <div class="item"><%= image_tag book.livre.imageurl %></div>
      <% end %>
    <% end %>

  <% else %>

    <% ec.each do |book| %>
      <%= link_to book_show_path(book, status: status) do  %>
        <div class="item"><%= image_tag book.livre.imageurl %></div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<%= link_to historique_path do  %>
  <i class="fas fa-bookmark" style="color: white"></i>
<% end %>


<%= link_to books_path do  %>
  <i class="fas fa-book"  style="color: white"></i>
  <% end %>
<%= link_to view_followers_path do  %>
  <i class="fas fa-users" style="color: white"></i>

<% end %>

</footer>

app/views/shared/_navbar.html.erb
<style>
  .logolivre {
    width: 40px;height: 40px;
  }
  .nav-link {
    color: white;
  }
</style>


<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to :back do  %>
      <i class="fas fa-arrow-left" style="color:white;font-size: 25px;"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" style="text-align: center" id="navbarCollapse">
      <ul class="navbar-nav m-auto">

        <li class="nav-item">
          <%= link_to 'Accueil', books_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/books/followers"  style="colortext-align:center">Ma communauté</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/books/historique"  style="colortext-align:center">Mon historique</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete ,class: 'nav-link' %>
        </li>
      </ul>
              <div class="nav-item">
          <div style="color:white;text-align:center;border-bottom:">
            <% if signed_in? %>
            <%= "#{current_user.first_name.capitalize} #{current_user.last_name.upcase}" %>
            <% end %>
          </div>
        </div>
    </div>
  </nav>
</header>