config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'books/search', to: 'searchs#index', as: :search
  get 'books/store', to: 'searchs#store', as: :store
  get 'books/index', to: 'books#index', as: :books
  get 'books/:id/show', to: 'books#show', as: :book_show
  get 'books/liste/:id/show', to: 'listes#show', as: :liste_show
  patch 'books/liste/:id/update', to: 'listes#update', as: :liste_update

  patch 'books/:id/update', to: 'books#update', as: :book_update
  delete 'books/:id/destroy', to: 'books#destroy', as: :book_destroy
  post 'books/:id/notation', to: 'books#update_notation', as: :post_notation

  post 'books/:id/tags', to: 'books#update_tag', as: :book_update_tag, defaults: {format: :json}
  post 'books/:id/like', to: 'books#update_like', as: :book_update_like, defaults: {format: :json}
  post 'books/searchAuthor', to: 'searchs#searchAuthor', as: :author_search, defaults: {format: :json}
  post 'admin/delete', to: 'admins#delete', as: :admin_delete, defaults: {format: :json}
  get 'admin/add', to: 'admins#add', as: :admin_add
  get 'admin/liste/store', to: 'admins#store', as: :admin_liste_store
  post 'admin/storeNewListe', to: 'admins#storeListe', as: :admin_store_liste

  get 'books/:id/notations', to: "notations#index", as: :notations
  get 'books/:id/reviews/new', to: "reviews#new", as: :new_review
  post 'books/:id/reviews/new', to: "reviews#create"
  delete 'books/:id/reviews/:id', to: "reviews#destroy"
  get 'books/:id/reviews', to: "reviews#index", as: :reviews
  get 'books/:id/consultReviews', to: "reviews#consult", as: :review_consult
  get 'books/:id/consultNotations', to: "notations#consult", as: :notation_consult
  get 'books/:id/viewnote', to: "notations#view", as: :view_note
  get 'books/:id/viewcomment', to: "reviews#view", as: :view_comment
  get 'books/:user/profil', to: "profils#show", as: :profil_show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'books/:user/followers', to: "followers#create", as: :add_follower
  get 'books/followers', to: "followers#index", as: :view_followers
  delete 'books/:user/followers', to: "followers#destroy", as: :destroy_follower

  post "books/:id/comment", to: "reviews#comment", as: :review_comment



  get "books/historique", to: "historiques#index", as: :historique
  get "books/admin", to: "admins#index", as: :admin


  resources :readings do
    resources :reviews, only: ['new','create']
  end

  namespace :user do
    root :to => "books#index"
  end



end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index

    @followers = Follower.where(user: current_user)
    @f = []

    @followers.each do |fol|
      user = []
      if Reading.where(user_id: fol.follower).where(status: 'ec').empty?
        user << 'none'
      else
        user <<Reading.where(user_id: fol.follower).where(status: 'ec').first.livre
      end
      user << User.find(fol.follower)
      @f << user
    end

  end

  def create
    @user = User.find(params[:user])
    @follow = Follower.new
    @follow.user = current_user
    @follow.follower = @user.id
    @follow.save
    redirect_to view_followers_path
  end

  def destroy
    @user = User.find(params[:user])
    @f = Follower.where(user: current_user, follower: @user.id).first
    Follower.destroy(@f.id)
    redirect_to view_followers_path
  end
end

app/views/followers/index.html.erb
<% content_for :meta_title do %>
  My books and me - Ma communauté
<% end %>


<style>
  .delete-user {
    padding-right: 5px;
    padding-top: 5px;
    height: 100%;
  }

  .btn-ghost {
    padding: 0;
  }
</style>


<div style="margin: 80px 0">
  <h1>Votre communauté</h1>
  <hr>

  <div id="follower-cards">

    <% @f.each do |user| %>

    <div id="bookcard" class="d-flex list-inline justify-content-between" style="width: 280px; margin: 8px">


      <% if user[0] == 'none' %>
      <%= image_tag "Couverture_Livre_Neutre.jpg", alt: "alttext" %>
      <% else %>
      <%= link_to liste_show_path(user[0], status: 'follow') do  %>
      <%= image_tag user[0].imageurl, alt: "alttext" %>
      <% end %>
      <% end %>

      <div class="d-flex flex-column align-items-center">
        <h2><%= user[1].first_name %></h2>
                <div class="d-flex list-inline justify-content-around">
          <div class="add-user btn-user">
            <%= link_to profil_show_path(user[1]), class: 'btn btn-sm btn-ghost' do %>
            <span><i class="fas fa-user" style="font-size: 12px;margin-top:3px" ></i>  Voir profil</span>
            <% end %>
          </div>


        </div>
      </div>
      <div class="delete-user btn-user">
        <%= link_to destroy_follower_path(user[1]), method: 'delete' do %>
        <i class="fas fa-times-circle" style="font-size: 24px"></i>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>