config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'books/search', to: 'searchs#index', as: :search
  get 'books/store', to: 'searchs#store', as: :store
  get 'books/index', to: 'books#index', as: :books
  get 'books/:id/show', to: 'books#show', as: :book_show
  get 'books/liste/:id/show', to: 'listes#show', as: :liste_show
  patch 'books/liste/:id/update', to: 'listes#update', as: :liste_update

  patch 'books/:id/update', to: 'books#update', as: :book_update
  delete 'books/:id/destroy', to: 'books#destroy', as: :book_destroy
  post 'books/:id/notation', to: 'books#update_notation', as: :post_notation

  post 'books/:id/tags', to: 'books#update_tag', as: :book_update_tag, defaults: {format: :json}
  post 'books/:id/like', to: 'books#update_like', as: :book_update_like, defaults: {format: :json}
  post 'books/searchAuthor', to: 'searchs#searchAuthor', as: :author_search, defaults: {format: :json}
  post 'admin/delete', to: 'admins#delete', as: :admin_delete, defaults: {format: :json}
  get 'admin/add', to: 'admins#add', as: :admin_add
  get 'admin/liste/store', to: 'admins#store', as: :admin_liste_store
  post 'admin/storeNewListe', to: 'admins#storeListe', as: :admin_store_liste

  get 'books/:id/notations', to: "notations#index", as: :notations
  get 'books/:id/reviews/new', to: "reviews#new", as: :new_review
  post 'books/:id/reviews/new', to: "reviews#create"
  delete 'books/:id/reviews/:id', to: "reviews#destroy"
  get 'books/:id/reviews', to: "reviews#index", as: :reviews
  get 'books/:id/consultReviews', to: "reviews#consult", as: :review_consult
  get 'books/:id/consultNotations', to: "notations#consult", as: :notation_consult
  get 'books/:id/viewnote', to: "notations#view", as: :view_note
  get 'books/:id/viewcomment', to: "reviews#view", as: :view_comment
  get 'books/:user/profil', to: "profils#show", as: :profil_show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'books/:user/followers', to: "followers#create", as: :add_follower
  get 'books/followers', to: "followers#index", as: :view_followers
  delete 'books/:user/followers', to: "followers#destroy", as: :destroy_follower

  post "books/:id/comment", to: "reviews#comment", as: :review_comment



  get "books/historique", to: "historiques#index", as: :historique
  get "books/admin", to: "admins#index", as: :admin


  resources :readings do
    resources :reviews, only: ['new','create']
  end

  namespace :user do
    root :to => "books#index"
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @ec = Reading.where(status: 'ec').where(user: current_user)
    @wl = Reading.where(status: 'wl').where(user: current_user)
    @done = Reading.where(status: 'done').where(user: current_user).order(startdate: :desc).first(10)
    @liste = Reading.where(status: 'liste').where(user: current_user)

    @el = Endinglist.all

  end

  def show
    @status = params[:status]
    if @status === "liste"
      redirect_to liste_show_path(params[:id])
    else

    @reading = Reading.find(params[:id])
    @tags = ActsAsTaggableOn::Tag.all.order(:name)

    if params[:status] == 'done'
      @notes = @reading.notation.split('/')
      tag = @reading.tags[0].name
      @crit = Critere.tagged_with(tag)
      @criteria = []
      @crit.each_with_index do |critere, index|
        @couple = []
        @couple << critere.name
        @couple << @notes[index]
        @criteria << @couple
      end
    else
      @notes = []
      @criteria = []
    end

    if @reading.tags == []
      @tag = []
    else
      @tag = @reading.tags[0].name
    end
  end

  end

  def update_tag
    reading = Reading.find(params[:id])
    reading.tags.each do |tag|
      reading.tag_list.remove(tag.name)
    end

    reading.tag_list.add(params[:cat])
    @tag = params[:cat]
    reading.save

    render json: {status: params}
  end

  def update_like
    id = params[:id]
    like = params[:act]
    r = Reading.find(id)
    if like == 'like'
      c = r.like.to_i + 1
      r.update(like: c)
    else
      c = r.unlike.to_i + 1
      r.update(unlike: c)
    end

    render json: {add: c, id: id, like: like}
  end

  def update
    r = Reading.find(params[:id])

    status = r.status
    if status == 'wl'
      r.update(status: 'ec')
    end
    if status == 'ec'
      r.update(startdate: Date.today)

      r.update(status: 'done')

    end
    redirect_to books_path
  end

  def update_notation

    r = Reading.find(params[:id])
    r.update(notation: params[:note])
    render json: {status: params}

  end


  def destroy
    Reading.destroy(params[:id])
    redirect_to books_path

  end


end

app/views/books/_slider_passif.html.erb
<style>
  .custom-range {
    color: red;
  }

  .sliderPassif {
    width: 100%;
    height: 20px;
    background: linear-gradient(to right, #99f430 0%,#f92307 100%);
    display: flex
  }

  .actived {
    background-color: transparent;
  }

  .desactived {
    background-color: #fff;
  }

  .b {
    width: 10%;
    cursor: pointer;
  }
</style>



<div class="sliderPassif" style="border: 1px solid black">
  <% 10.times do |t| %>
    <% if pos.to_i <= t %>
      <div data-id="<%= t %>" class="b desactived"></div>
    <% else %>
      <div data-id="<%= t %>" class="b actived"></div>
    <% end %>
  <% end %>

</div>

app/views/books/index.html.erb
<% content_for :meta_title do %>
  My books and me - Accueil
<% end %>
<div style="margin-bottom: 80px;margin-top: 66px">

  <div class="titre">Mes lectures du moment</div>
  <div class="ligne">

    <%= render 'shared/carousel', ec: @ec, status: 'ec', ajout: true %>
  </div>
  <div class="titre">Ma Wish list</div>
  <div class="ligne">

    <%= render 'shared/carousel', ec: @wl, status: 'wl', ajout: true  %>
  </div>
  <div class="titre">Mes 10 dernières lectures</div>
  <div class="ligne">

    <%= render 'shared/carousel', ec: @done, status: 'done', ajout: false  %>
  </div>

  <% @el.each do |liste| %>
  <div class="titre"  style="background-color: #292929"><%= liste.name %></div>
  <div class="ligne" style="background-color: #292929">

    <%= render 'shared/carousel', ec: liste.endings, status: 'liste', ajout: false %>
  </div>
  <% end %>


</div>

app/views/books/show.html.erb
<style>
  .icone {
    width: 70px;
    text-align: center;
    margin: 0 auto;
  }
</style>

<% content_for :meta_title do %>
  My books and me - <%= @reading.livre.title %>
<% end %>



<%= csrf_meta_tag %>
<div class="container" style="margin-top: 80px">
  <div class="haut" style="display: flex;justify-content: space-between;">
    <h1><%= @reading.livre.title %></h1>



  </div>
  <hr>
  <div class="middle" style="display: flex;justify-content: space-between;">
    <div style="font-style: italic"><%= @reading.livre.author %></div>
        <% if @reading.status == 'done' %>
      <h3><%= @reading.tags[0].name %> </h3>
    <% end %>
    <% if @reading.status == 'ec' %>
    <% if @tag== []  %>
    <% s = "data-tag=none" %>
    <% else %>
    <% s = "data-tag=#{@tag}" %>
    <% end %>
    <div id="tag" <%= s  %> data-toggle="modal" data-target="#exampleModal" style="cursor: pointer;">
      <% if @tag == [] %>
      <button class="btn btn-sm m-0" style="color: white">Définir catégorie</button>
      <% else %>
      <%= @tag %>
      <% end %>
      <% end %>
    </div>
  </div>
  <hr>
  <div id="bookcard" class="p-4 container" style="">
    <!--     <div class="haut"> -->
      <div class="haut">
        <div class="gauche">
          <%= image_tag @reading.livre.imageurl, alt: "alttext", class: "image" %>
        </div>
        <div class="droite" style="flex-grow: 1">
          <div class="comment" style="overflow-x: hidden;">
            <div class="allcomment p-2" style="height: 300px;font-size: 1rem;font-size: bold">
              <%= @reading.livre.description.html_safe if !@reading.livre.description.nil? %>
            </div>
          </div>

        </div>
      </div>
      <div class="bas d-flex justify-content-between w-100">
        <div class="gauche" style="width: 100px;display: flex;justify-content: space-between;margin-top: 30px">
          <div>
            <%= link_to notation_consult_path(@reading,status: @reading.status) do  %>
            <i class="fas fa-list-ol" style="font-size: 2rem"></i>
            <% end %>
          </div>
          <div>
            <%= link_to review_consult_path(@reading, status: @reading.status)  do%>
            <i class="fas fa-comments"  style="font-size: 2rem"></i>
            <% end %>
          </div>
        </div>
        <% if @reading.status== 'ec' %>
        <div id="btnNote" hidden>

          <%= link_to 'Noter ce livre', notations_path(@reading) , class: "btn btn-success m-0 text-left", style: "color: white; font-weight: bold"  %>
        </div>
        <% end %>
        <div style="width: auto;display: flex;justify-content: end;margin-top: 30px;">
          <% if @reading.status == 'wl' %>
          <div class="icone">
            <%= link_to book_update_path(@reading), method: 'patch' do  %>
            <i class="fas fa-book-reader" style="font-size: 2rem"></i>
            <% end %>
          </div>
          <div  class="icone">
            <button id="btnbuy" style="background-color: transparent; border: none; padding-right: 16px"><i class="fas fa-credit-card" style="font-size: 2rem"></i></button>

          </div>

          <div  class="icone">
           <%= link_to book_destroy_path(@reading), method: 'delete' do  %>
           <i class="fas fa-trash-alt" style="font-size: 2rem;color: red"></i>
           <% end %>
         </div>

         <% end %>
         <% if @reading.status == 'ec' %>


         <div  class="icone">
           <%= link_to book_destroy_path(@reading), method: 'delete' do  %>
           <i class="fas fa-trash-alt" style="font-size: 2rem;color: red"></i>
           <% end %>
           <% end %>
         </div>

       </div>

     </div>
     <hr>
     <div class="info container" style="padding: 30px">
       <% if @status == 'done' %>
       <div style="font-size: 2rem">
        indice : <%= @reading.indice %>
      </div>
      <hr>
      <div>
        <div>
          Satisfaction globale
          <%= render 'slider_passif', pos: @notes[-1] %>
        </div>
        <hr>
        <% @criteria.each do |critere| %>
        <div>
          <%= critere[0] %>
          <%= render 'slider_passif', pos: critere[1] %>
        </div>
        <% end %>
      </div>
      <hr>
      <div style="margin-bottom: 120px">
        <form action="" method="post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group">
            <div style="display: flex; justify-content: space-between;">
              <p>votre commentaire :</p>
              <%= link_to new_review_path(@reading) do  %>
              <i class="fas fa-edit"></i>
              <% end %>
            </div>
            <textarea rows=7 class="form-control" name="commentaire"><%= @reading.comment %></textarea>
            <div>
              <% if @reading.public %>
              <%=  "commentaire public" %>
              <% else %>
              <%= "commentaire privé" %>
              <% end %>
            </div>
            <hr>
            <p>Vos sentiments</p>
            <div style="font-size: 0.7rem">De manière plus intime, vous pouvez inscrire ici les conditions (événement, actualité, situation sentimentale, etc...) présentes au moment où vous avez lu ce livre</div>
            <textarea class="form-control" name="feeling"><%= @reading.feeling %> </textarea>
            <hr>
            <p>Comment avez-vous découvert ce livre ?</p>
            <div><%= @reading.discover %> </div>
          </div>
        </form>
      </div>
      <% end %>
      <div class="bas">



        <div class="icons" >
          <%= link_to "https://www.fnac.com/SearchResult/ResultList.aspx?SCat=0%211&Search=#{@reading.livre.title}&sft=1&sa=0", target: "_blank" do   %>
          <div><%= image_tag ( "fnac.png")%></div>
          <% end %>
          <%= link_to "https://www.cultura.com/catalogsearch/result/?q=#{@reading.livre.title}&classification=27674&mode=grid&p=1", target: "_blank" do   %>
          <div><%= image_tag ( "cultura.png") %></div>
                    <% end %>
          <%= link_to "https://www.amazon.fr/s?k=#{@reading.livre.title}&i=stripbooks&__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss", target: "_blank" do  %>
          <div><%= image_tag ( "amazon.png")%></div>
          <% end %>
          <%= link_to "https://www.rueducommerce.fr/recherche/#{@reading.livre.title}?sort=score&universe=MC-6854&view=list", target: "_blank" do  %>

          <div><%= image_tag ( "rdcc.png")%></div>
                    <% end %>

        </div>


        <% if @reading.status == 'ec' %>
        <div id="avertissement">
          <div class="card">
            Vous devez définir une catégorie avant de noter ce livre.
          </div>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- <script src="jquery.min.js"></script>
<script src="rangeslider.min.js"></script>
<script>
$('input[type="range"]').rangeslider();
</script>
-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Définissez la catégorie</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <% @tags.each do |t| %>
          <% if t.name == @tag %>
          <%  act="data-active=true" %>
          <% else %>
          <%  act="data-active=false" %>
          <% end %>
          <div class="badge" data-reading="<%= @reading.id %>" data-cat="<%= t.name  %>" data-id="<%= @reading.livre.id %>" <%= act %> data-color="<%= t.color %>" ><%= t.name %></div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>