config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'books/search', to: 'searchs#index', as: :search
  get 'books/store', to: 'searchs#store', as: :store
  get 'books/index', to: 'books#index', as: :books
  get 'books/:id/show', to: 'books#show', as: :book_show
  get 'books/liste/:id/show', to: 'listes#show', as: :liste_show
  patch 'books/liste/:id/update', to: 'listes#update', as: :liste_update

  patch 'books/:id/update', to: 'books#update', as: :book_update
  delete 'books/:id/destroy', to: 'books#destroy', as: :book_destroy
  post 'books/:id/notation', to: 'books#update_notation', as: :post_notation

  post 'books/:id/tags', to: 'books#update_tag', as: :book_update_tag, defaults: {format: :json}
  post 'books/:id/like', to: 'books#update_like', as: :book_update_like, defaults: {format: :json}
  post 'books/searchAuthor', to: 'searchs#searchAuthor', as: :author_search, defaults: {format: :json}
  post 'admin/delete', to: 'admins#delete', as: :admin_delete, defaults: {format: :json}
  get 'admin/add', to: 'admins#add', as: :admin_add
  get 'admin/liste/store', to: 'admins#store', as: :admin_liste_store
  post 'admin/storeNewListe', to: 'admins#storeListe', as: :admin_store_liste

  get 'books/:id/notations', to: "notations#index", as: :notations
  get 'books/:id/reviews/new', to: "reviews#new", as: :new_review
  post 'books/:id/reviews/new', to: "reviews#create"
  delete 'books/:id/reviews/:id', to: "reviews#destroy"
  get 'books/:id/reviews', to: "reviews#index", as: :reviews
  get 'books/:id/consultReviews', to: "reviews#consult", as: :review_consult
  get 'books/:id/consultNotations', to: "notations#consult", as: :notation_consult
  get 'books/:id/viewnote', to: "notations#view", as: :view_note
  get 'books/:id/viewcomment', to: "reviews#view", as: :view_comment
  get 'books/:user/profil', to: "profils#show", as: :profil_show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'books/:user/followers', to: "followers#create", as: :add_follower
  get 'books/followers', to: "followers#index", as: :view_followers
  delete 'books/:user/followers', to: "followers#destroy", as: :destroy_follower

  post "books/:id/comment", to: "reviews#comment", as: :review_comment



  get "books/historique", to: "historiques#index", as: :historique
  get "books/admin", to: "admins#index", as: :admin


  resources :readings do
    resources :reviews, only: ['new','create']
  end

  namespace :user do
    root :to => "books#index"
  end



end

app/controllers/notations_controller.rb
class NotationsController < ApplicationController
  def index


    @reading = Reading.find(params[:id])
    tag = @reading.tags[0].name
    @taglist = Critere.tagged_with(tag)


  end


  def consult
    if params[:status] == 'liste'
      @livre = Livre.find(params[:id])

    else
      @livre = Reading.find(params[:id]).livre
    end
    @readings = Reading.where(livre: @livre).where(status: 'done')

    @readings = @readings.sort_by {| item | item.indice}.reverse if !@readings.empty?

  end

  def view

    @other_reading = Reading.find(params[:id])
    @other_notes = @other_reading.notation.split('/')


    livre = @other_reading.livre
    @my_reading = Reading.where(user: current_user).where(livre: livre)[0]
    if !@my_reading.notation.nil?
      @my_notes = @my_reading.notation.split('/')
    end

  end


end

app/views/notations/_listenote.html.erb
<% Critere.tagged_with(reading.tags[0]).each_with_index do |tag, index| %>
  <div id="<%= index %>">
    <div ><%= tag.name %></div>
    <%= render 'books/slider_passif', pos: 3, status: "slide#{index}"  %>
  </div>
<% end %>

app/views/notations/_slider.html.erb
<style>
  .custom-range {
    color: red;
  }

  .slider {
    width: 90%;
    height: 20px;
    background: linear-gradient(to right, #99f430 0%,#f92307 100%);
    display: flex
  }

  .actived {
    background-color: transparent;
  }

  .desactived {
    background-color: #fff;
  }

  .boite {
    width: 10%;
    border-right: 0.2px dotted black;
    cursor: pointer;
  }
</style>

<div class="slider" style="border: 1px solid black">
  <div data-id="1" class="boite desactived"></div>
  <div data-id="2" class="boite desactived"></div>
  <div data-id="3" class="boite desactived"></div>
  <div data-id="4" class="boite desactived"></div>
  <div data-id="5" class="boite desactived"></div>
  <div data-id="6" class="boite desactived"></div>
  <div data-id="7" class="boite desactived"></div>
  <div data-id="8" class="boite desactived"></div>
  <div data-id="9" class="boite desactived"></div>
  <div data-id="10" class="boite desactived" style="border: none"></div>
</div>

app/views/notations/consult.html.erb
<style>
  .avat {
    width: 55px;
    height: 55px;
    color: white;
    font-size: 20px;
    text-align: center;
    background-color: red;
    border-radius: 50%;
    line-height: 55px;
  }
</style>

<% content_for :meta_title do %>
  My books and me - <%= @livre.title %>
<% end %>

<div class="container" style="margin-top: 100px; margin-bottom: 100px">
  <h1 class="mb-3">Les indices des lecteurs</h1>
  <h3>Titre : <%= @livre.title %></h3>
  <h4>Auteur: <%= @livre.author %></h4>

    <% if @readings.empty? %>
              <div style="background-color: yellow;padding: 16px;text-align: center">
                  Ce livre n'a pas encore reçu de notes
              </div>

    <% else %>

    <% @readings.each do |reading| %>

        <% if reading.user == current_user  %>
          <div class="liste" style="background-color: rgba(0,0,255,0.2)">
        <% else %>
          <div class="liste">
        <% end %>

        <div class="row  align-items-center">
                    <div class="col-2">
                      <%= link_to profil_show_path(reading.user) do  %>
                        <div class="avat" style="background-color: #1d6ab7">
                          <%= "#{reading.user.first_name[0].upcase} #{reading.user.last_name[0].upcase}" %>
                        </div>
                      <% end %>
                    </div>

                    <div class="col-6">
                      <div style="font-size: 1.5rem">
                        <div class="name"><%= reading.user.first_name %></div>
                        <div class="date"><%= reading.startdate.strftime("%d %B  %Y") %></div>
                      </div>
                    </div>

                    <div class="col-2">
                      <div>
                        <% if (!reading.comment.nil? && reading.public) %>
                          <button class="btn btn-sm comment" style="color: white; background-color: #1d6ab7">commentaire</button>
                        <% end %>
                      </div>
                    </div>

                    <div class="col-2">
                      <%= link_to view_note_path(reading) do %>
                        <div  style="width: 55px;height: 55px; border-radius:50%;border: 2px solid #1d6ab7; background-color: white; text-align: center; line-height: 55px; font-weight: bold"><%= reading.indice %></div>
                      <% end %>
                    </div>
                  </div>


        </div>
        <% if (!reading.comment.nil? && reading.public) %>
              <div class="liste" style="display: none;height: auto">
                  <p><small><%= time_ago_in_words(reading.updated_at)  %> ago</small></p>
                  <div><%= reading.comment %></div>
              </div>
        <% end %>



              <% end %>


    <% end %>
  </div>

  <!-- Button trigger modal -->

app/views/notations/index.html.erb
<% content_for :meta_title do %>
  My books and me - mes notes
<% end %>

<div id="notation-container" style="margin-top: 100px">
  <input type="hidden" value=" <%= @reading.id %> " id="reading">
  <h1>Qu'avez-vous pensé de cette oeuvre ?</h1>
  <div class="notations mb-5">
    <% @taglist.each_with_index do |tag, index| %>
    <div id="<%= index %>" class="criteria" data-pos="0">
      <div style="font-size: 16px"><%= tag.name %></div>
      <%= render 'slider', status: "slide#{tag.id}"  %>
    </div>
    <% end %>
    <hr>
    <div id="<%= 99 %>" class="mt-3" data-pos="0">
      <div >Ce livre vous a-t-il plu ?</div>
      <%= render 'slider', status: "slide99"  %>
    </div>
  </div>

  <div>
  <p>Voulez-vous écrire un commentaire ?</p>

  <%= link_to "Non merci", review_comment_path(@reading, status: 'false'), method: 'post', class: "btn btn-lg btn-danger d-block w-100 mb-5"%>

  <%= link_to "J'y vais !", review_comment_path(@reading, status: 'true'),  method: 'post', class: "btn btn-lg btn-primary d-block w-100 mb-5"%>
  </div>
</div>

app/views/notations/view.html.erb
<% content_for :meta_title do %>
  My books and me - mes notes
<% end %>

<div style="margin: 100px 0">
  <div class="container" style="margin: 0 24px">

    <div style="display: flex;width: 40%;margin: 0 auto;justify-content: space-between;">
      <% if !@my_notes.nil? %>
      <div class="indices" >
        <div><small>Moi</small></div>
        <div><%= @my_reading.indice %></div>
      </div>
      <% end %>
      <div class="indices">
        <div><small><%= @other_reading.user.first_name %></small></div>
        <div><%= @other_reading.indice %></div>
      </div>
    </div>

    <div class="mb-5" style="margin: 24px 0">
      <% Critere.tagged_with(@other_reading.tags[0]).each_with_index do |tag, index| %>
      <div id="<%= index %>">
        <div style="font-weight: bold"><%= tag.name %></div>
        <% if !@my_notes.nil? %>
          <div style="font-weight: italic" class="mb-2">
            <%= 'Moi' %><%= render 'books/slider_passif', pos: @my_notes[index], status: "slide#{index}"  %>
          </div>
        <% end %>
        <div style="font-weight: italic">
          <%= @other_reading.user.first_name %><%= render 'books/slider_passif', pos: @other_notes[index], status: "slide#{index}"  %>
        </div>
      </div>
      <hr>
      <% end %>
<hr>
      <div id="99">
        <div style="font-weight: bold">Satisfaction générale</div>
        <% if !@my_notes.nil? %>
        <div style="font-weight: italic" class="mb-2">
          <%= 'Moi' %><%= render 'books/slider_passif', pos: @my_notes[-1], status: "slide99"  %>
        </div>
        <% end %>
        <div style="font-weight: italic">
          <%= @other_reading.user.first_name %><%= render 'books/slider_passif', pos: @other_notes[-1], status: "slide99"  %>
        </div>
      </div>
      <hr>
    </div>

  </div>

</div>